site_name: Parse Studio

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.tabbed
    - content.image.figure
    - content.image.lightbox
    - content.image.zoom
    - content.video
    - content.iframe
    - content.math
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: lime
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: purple-grey
      accent: lime

plugins:
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
  - autorefs


nav:
  - Home:
    - Welcome to Parse Studio: index.md
  - Docling Parser:
      - Overview: parsers/docling_parser.md
  - Llama Parser:
      - Overview: parsers/llama_parser.md
  - PmuPDF Parser:
      - Overview: parsers/pymupdf_parser.md



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
