name: CI - Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.md'
      - 'docs/**'
      - 'images/**'
      - 'LICENSE'
      - '.github/workflows/ci-docs.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.md'
      - 'docs/**'
      - 'images/**'
      - 'LICENSE'
      - '.github/workflows/ci-docs.yml'

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Check Markdown files
      uses: DavidAnson/markdownlint-cli2-action@v17
      with:
        globs: |
          **/*.md
          !node_modules/**/*.md

    - name: Check links in markdown
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/markdown-link-check-config.json'
        folder-path: '.'
        file-extension: '.md'

    - name: Validate images exist
      run: |
        echo "Checking if referenced images exist..."
        # Check if logo exists
        if [ -f "images/logo.webp" ]; then
          echo "✓ Logo found: images/logo.webp"
        else
          echo "✗ Logo not found: images/logo.webp"
          exit 1
        fi

        # Check LICENSE file exists
        if [ -f "LICENSE" ]; then
          echo "✓ LICENSE file found"
        else
          echo "✗ LICENSE file not found"
          exit 1
        fi

    - name: Check README structure
      run: |
        echo "Validating README.md structure..."

        # Check if required sections exist
        required_sections=("Installation" "Quick Start" "Contributing" "License")

        for section in "${required_sections[@]}"; do
          if grep -q "## .*$section" README.md; then
            echo "✓ Found section: $section"
          else
            echo "✗ Missing section: $section"
            exit 1
          fi
        done

        echo "✓ All required sections found in README.md"
