name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, windows-latest]
        python-version: ['3.12.7']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Users\runneradmin\AppData\Roaming\Python\Scripts", [System.EnvironmentVariableTarget]::Process)

      - name: Install Poetry (MacOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install System Dependencies (MacOS Only)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install zlib mupdf openssl libffi libjpeg libpng geos
        shell: bash

      - name: Add PKG_CONFIG_PATH (MacOS Only)
        if: runner.os == 'macOS'
        run: echo "PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/lib/pkgconfig" >> $GITHUB_ENV
        shell: bash


      - name: Verify Poetry Installation
        run: poetry --version
        shell: bash

      - name: Configure Poetry Environment
        run: poetry env use python
        shell: bash

      - name: Clear Poetry Cache
        run: poetry cache clear pypi --all
        shell: bash

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root --verbose
        shell: bash

      - name: Run Tests
        run: poetry run pytest
        shell: bash
